P=int(input("ENTER THE PRINCIPAL : "))
R=int(input("ENTER THE RATE OF INTEREST : "))
T=int(input("ENTER THE TIME PERIOD : "))
S=(P*R*T)/100
print("THE SIMPLE INTREST IS : ",S)
```

    ENTER THE PRINCIPAL : 20
    ENTER THE RATE OF INTEREST : 10
    ENTER THE TIME PERIOD : 5
    THE SIMPLE INTREST IS :  10.0
