a=int(input("ENTER THE 1ST DIGIT : "))
b=int(input("ENTER THE 2ND DIGIT : "))
c=a%b
print("THE REMINDER WHEN 1ST DIGIT IS DIVIDED BY 2ND DIGIT IS : ",c)
```

    ENTER THE 1ST DIGIT : 4
    ENTER THE 2ND DIGIT : 2
    THE REMINDER WHEN 1ST DIGIT IS DIVIDED BY 2ND DIGIT IS :  0
