A=int(input("ENTER THE DIGIT TO FIND NEGATIVE , POSITIVE OR ZERO : "))
if A==0:
    print("THE GIVEN VALUE IS ZERO.")
elif A>0:
    print("THE GIVEN VALUE IS POSITIVE.")
else:
    print("THE GIVEN VALUVE IS NEGATIVE.")
```

    ENTER THE DIGIT TO FIND NEGATIVE , POSITIVE OR ZERO : -10
    THE GIVEN VALUVE IS NEGATIVE.
