a=input("ENTER THE VALUE OF A : ")
b=input("ENTER THE VALUE OF B : ")
c=a
a=b
b=c
print("THE VALUE OF A AND B AFTER SWAPPING ARE ",a,b , "RESPECTIVELY")
```

    ENTER THE VALUE OF A : 2
    ENTER THE VALUE OF B : 55
    THE VALUE OF A AND B AFTER SWAPPING ARE  55 2 RESPECTIVELY
